### PR TITLE
MacroTools down to 0.3.1 is actually fine

### PR DESCRIPTION
**Pull request by tkelman**
I was misled on this one by a bad tag on MacroTools that didn't have the "v" prefix
v0.3.0 fails to load on Julia 0.6, but v0.3.1 passes tests here

### CODE REVIEW

**Comment by bramtayl** [comment]
Ok thanks!

**Comment by tkelman** [comment]
wrong button?

**Comment by bramtayl** [comment]
hopefully i did it right this time?

**Comment by tkelman** [comment]
yep, thanks

**Pull request merged**
